# .markdownlint.yaml
# See: https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml
##
# Default state for all rules with a few changes below
default: true

# Path to configuration file to extend
extends: null

# MD013/line-length - Line length
# Don't enforce this
MD013: False
